<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFhdAcan\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFhdAcan/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFhdAcan.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFhdAcan\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFhdAcan\appAppKernelProdContainer([
    'container.build_hash' => 'FhdAcan',
    'container.build_id' => 'cec7d568',
    'container.build_time' => 1733756210,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFhdAcan');
